### ISSUE TITLE
question: toolbar ?

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#36]
Where does the toolbar come from in the screencast in the readme ?
I do not have a toolbar...

**Comment by gepd** [comment]
I'm removing the toolbar because it was only full compatible with windows 8-10
In the next release I'll add an alternative cross-platform, if you are using windows 8 or 10 you can go to the `Devior/Preset` folder and rename the `Main.sublime-menu.windows` to `Main.sublime-menu` and you should have the toolbar back

**Comment by tablatronix** [comment]
Ah thanks still on 7
